In [18]:
import numpy as np

arr = np.random.randint(1,20,size=(4,4))
print(arr)


[[ 6 16 13 15]
 [ 5  9  8 16]
 [19 11 11 10]
 [ 2  2  4 19]]


In [12]:
x = int(input("Enter number: "))
arr2 = np.full((3,4),x)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
arr3 = np.full((2,5),1,dtype = int)
print(arr3)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
arr4 = np.arange(10,50,2)
print(arr4)
arr5 = np.linspace(0,1,10)
print(arr5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
li = [1,2,3,4,5]
arr6 = np.array(li)
print(arr6)

[1 2 3 4 5]


In [20]:
arr7 = np.arange(0,10,1)
print(arr7)
arr7[4] = 99
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 99  5  6  7  8  9]
