In [1]:
import numpy as np

arr = np.random.randint(1,20,size=(4,4))
print(arr)


[[ 7 17 16  5]
 [13 13 12  1]
 [14 11  1  6]
 [11 19 19  4]]


In [12]:
x = int(input("Enter number: "))
arr2 = np.full((3,4),x)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
arr3 = np.full((2,5),1,dtype = int)
print(arr3)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
arr4 = np.arange(10,50,2)
print(arr4)
arr5 = np.linspace(0,1,10)
print(arr5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
li = [1,2,3,4,5]
arr6 = np.array(li)
print(arr6)

[1 2 3 4 5]


In [20]:
arr7 = np.arange(0,10,1)
print(arr7)
arr7[4] = 99
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 99  5  6  7  8  9]


In [5]:
arr8 = np.full((5,5),1)
arr8[1:-1,1:-1] = 0
arr8[2:-2,2:-2] = 9
print(arr8)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [23]:
arr9 = np.arange(1,31).reshape(6,5)
print(arr9)
arr9[[0,1,2,3],[1,2,3,4]]
arr9[[0,-2,-1],-2:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])